package com.aizen.service;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Hand-picked, stable resource links for each career sector used by the "To The Point"
 * feature. These are curated by hand and never generated by the AI, so a suggested link
 * can never be broken, fake or hallucinated - only the sector matching step uses AI.
 */
public final class CareerResourceData {

    public record Resource(String title, String type, String url, String description) {
    }

    private static final Map<String, List<Resource>> RESOURCES = new LinkedHashMap<>();

    static {
        RESOURCES.put("Software Engineering", List.of(
                new Resource("roadmap.sh", "Roadmap", "https://roadmap.sh",
                        "Step-by-step learning roadmaps for every developer track."),
                new Resource("LeetCode", "Practice", "https://leetcode.com",
                        "Practice the data-structure & algorithm questions companies actually ask."),
                new Resource("freeCodeCamp", "Course", "https://www.freecodecamp.org",
                        "Free, project-based courses covering the full stack."),
                new Resource("GitHub", "Portfolio", "https://github.com",
                        "Host your projects so interviewers can see real, working code.")
        ));
        RESOURCES.put("Data Science / AI", List.of(
                new Resource("Kaggle", "Practice", "https://www.kaggle.com",
                        "Real datasets and competitions to build a public portfolio."),
                new Resource("Google ML Crash Course", "Course",
                        "https://developers.google.com/machine-learning/crash-course",
                        "Free, well-structured introduction to core ML concepts."),
                new Resource("fast.ai", "Course", "https://www.fast.ai",
                        "Practical, code-first deep learning course."),
                new Resource("Towards Data Science", "Reading", "https://towardsdatascience.com",
                        "Ongoing articles on tools, techniques and interview prep.")
        ));
        RESOURCES.put("Marketing", List.of(
                new Resource("HubSpot Academy", "Course", "https://academy.hubspot.com",
                        "Free certifications in inbound marketing, SEO and content strategy."),
                new Resource("Google Digital Garage", "Course",
                        "https://learndigital.withgoogle.com/digitalgarage",
                        "Google's own free digital marketing fundamentals course."),
                new Resource("Neil Patel Blog", "Reading", "https://neilpatel.com/blog",
                        "Practical, up-to-date marketing and SEO strategy articles.")
        ));
        RESOURCES.put("Sales", List.of(
                new Resource("HubSpot Sales Blog", "Reading", "https://blog.hubspot.com/sales",
                        "Frameworks for prospecting, objection handling and closing."),
                new Resource("Salesforce Trailhead", "Course", "https://trailhead.salesforce.com",
                        "Free, guided modules on sales process and CRM tools.")
        ));
        RESOURCES.put("Finance & Accounting", List.of(
                new Resource("Corporate Finance Institute", "Course", "https://corporatefinanceinstitute.com",
                        "Free lessons on financial modelling, valuation and accounting basics."),
                new Resource("Investopedia", "Reading", "https://www.investopedia.com",
                        "Clear explanations of financial terms, statements and concepts.")
        ));
        RESOURCES.put("Human Resources", List.of(
                new Resource("SHRM", "Community", "https://www.shrm.org",
                        "The leading HR professional body - articles, templates and research."),
                new Resource("HRCI", "Certification", "https://www.hrci.org",
                        "Recognised HR certifications employers look for.")
        ));
        RESOURCES.put("Customer Service", List.of(
                new Resource("HubSpot Service Blog", "Reading", "https://blog.hubspot.com/service",
                        "Best practices for support conversations and customer satisfaction."),
                new Resource("Help Scout Blog", "Reading", "https://www.helpscout.com/blog",
                        "Practical guides on tone, empathy and handling difficult tickets.")
        ));
        RESOURCES.put("Project Management", List.of(
                new Resource("PMI", "Certification", "https://www.pmi.org",
                        "Home of the PMP certification and core PM standards."),
                new Resource("Atlassian Agile Coach", "Guide", "https://www.atlassian.com/agile",
                        "Free, practical guide to Agile, Scrum and Kanban.")
        ));
    }

    private CareerResourceData() {
    }

    /** Curated resources for the sector, or an empty list if the sector is unknown. */
    public static List<Resource> forSector(String sector) {
        return RESOURCES.getOrDefault(sector, List.of());
    }
}